config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "charts#home"
  
  resources :users, only: [:new, :create] do
    collection do  
      get "login" => "users#login_form"
      post "login" => "users#login"
      post "logout" => "users#logout"
    end
  end

  resources :charts, only: [:new, :create, :index] do
    collection do
      get "home", to: "charts#home"
    end
  end

  resources :comments, only: [:index, :new, :create, :delete]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
  validates :weight, presence: true, numericality: {only_integer: true}
  validates :user_id, presence: true
  
  belongs_to :user
  belongs_to :difference
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :difference
  belongs_to :user
end

app/models/difference.rb
class Difference < ApplicationRecord
  has_many :charts
  has_many :comments
  belongs_to :user

  def total_weight(new_data)
    require 'data'
    sum = Difference.where(session[:user_id]).where(sunday: false)
    new_total = sum + new_data
    if Date.today == sunday
      new_total[:sunday] = true
      new_total.update
    else
      new_total.update
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :password, presence: true, uniqueness: true, length: { minimum: 3, maximum: 15}
  validates :height, presence: true, length: {minimum: 3, maximum: 3 }
  has_many :charts
  has_many :differences
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  def home
  end
  
  def new
    @weight = Chart.new
  end

  def create
    user = User.find_by("#{session[:user_id]}")
    Chart.create(weight_params)
    total_wight(weight_params)
    redirect_to charts_path
  end

  def index
    @user_id = session[:user_id]
    @data = Chart.where(user_id: @user_id)
    @data_weight = @data.pluck(:weight)
    # @date = data.pluck(:created_at)
    # @days = make_date(date)
    user_data = User.find_by(id: @user_id)
    height = user_data.height
    @bmi = bmi_calc(@data_weight, height)
    @start = @data.first
  end
  

  def bmi_calc(weights, height)
    last = weights.last
    if last.nil?
      render new_chart_path
    else
      calc_height = height / 100.to_f
      bmi = last / calc_height / calc_height
    end
  end


  private
  def weight_params
    params.require(:chart).permit(:weight).merge(user_id: session[:user_id])
  end
  # def make_date(date)
  #   n = []
  #   date.each do |d|
  #     i = d.created_at.strftime('%Y/%m/%d')
  #   end
  #   n << i
  # end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index 
    difference = Difference.where(user_id: session[:user_id])
    d_id = difference.pluck(:id)
    @comments = Comment.where(difference_id: d_id).includes(:user)
    @graph = difference.pluck(:total)
    binding.pry
    @comment = Comment.new
    
  end

  def new
  end

  def create
    @comment.create(params_comment)
    link_to comments_path
  end

  def delete
    @comment.delete
    link_to comments_path
  end

  private
  def params_comment
    params.require(:comment).permit(:comment).merge(user_id: session[:user_id], difference_id: @graph.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(params_user_info)
    if @user.save
      session[:user_id]= @user.id
      flash[:notice] = "登録完了です"
      redirect_to new_chart_path
    else
      flash[:notice] ="登録できません"
      render new_user_path
    end
  end


  def login_form
    @user = User.new
  end

  def login
    @user = User.find_by(name: params[:name], password: params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to new_chart_path
    else
      flash[:notice]="入力情報が間違っています"
      render "users/login_form"
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to login_users_path
  end

  private
  def params_user_info
    params.require(:user).permit(:name, :password, :height)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charts/home.html.erb
<div class="top">
  <%= image_tag "/assets/sunrize_road.jpg", class: :image %>
</div>

app/views/charts/index.html.erb
<div class="chart">
  <div class="chart_content">
    <div class="mychart">
        <h1>体重の推移</h1><br>

        <canvas id="myChart" width="-400" height="-400" ></canvas>
        <script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: [1,2,3,4,5,6,7],
                    datasets: [{
                    label: '体重の推移',
                        data: <%= @data_weight %>,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            // 'rgba(54, 162, 235, 0.2)',
                            // 'rgba(255, 206, 86, 0.2)',
                            // 'rgba(75, 192, 192, 0.2)',
                            // // 'rgba(153, 102, 255, 0.2)',
                            // 'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            // 'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                        //     'rgba(255, 206, 86, 1)',
                        //     'rgba(75, 192, 192, 1)',
                        //     'rgba(153, 102, 255, 1)',
                        //     'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        </script>
    </div>
    <div class="chart_info">
      <P>・縦 : 体重(Kg)<br>
         ・横 : 経過日<%= "(#{@data.length}日目)" %>
      </p>
      <%= "・今日のBMI : #{@bmi.round(2)}" %>
      <p>・初日：<%= @start.created_at.strftime('%Y/%m/%d') %></p>
    </div>
    <div class="link_to">
      <%= link_to "詳細画面へ", comments_path, class: :to_input_btn %>
    </div>
  </div>
</div>

app/views/charts/new.html.erb
<div class="input">
  <div class="input_form">
    <h3>体重を入力</h3>
    <%= form_with(model: @weight, local: true) do |f| %>
      <%= f.text_field :weight, placeholder: "           今日の努力", row: "2" %><br>
      <%= f.submit "Input", class: :input_btn %>
    <% end %>
    <%= link_to "グラフをみる", charts_path, class: :to_chart_btn %>
  </div>
</div>

app/views/comments/index.html.erb
<div class="wrapper">
  <div class="contents">
    <div class="graph">
      <p class="user_name">棒グラフ</p>
      <canvas id="myBarChart"></canvas>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

        <script>
          var ctx = document.getElementById("myBarChart");
          var myBarChart = new Chart(ctx, {
            type: 'bar',
            data: {
              labels: ['8月1日', '8月2日', '8月3日', '8月4日', '8月5日', '8月6日', '8月7日'],
              datasets: [
                {
                  label: 'A店 来客数',
                  data: [6, 6, 9, 8, 5, 6, 4],
                  backgroundColor: "rgba(219,39,91,0.5)"
                // },{
                //   label: 'B店 来客数',
                //   data: [55, 45, 73, 75, 41, 45, 58],
                //   backgroundColor: "rgba(130,201,169,0.5)"
                // },{
                //   label: 'C店 来客数',
                //   data: [33, 45, 62, 55, 31, 45, 38],
                //   backgroundColor: "rgba(255,183,76,0.5)"
                }
              ]
            },
            options: {
              title: {
                display: true,
                text: '支店別 来客数'
              },
              scales: {
                yAxes: [{
                  ticks: {
                    suggestedMax: 10,
                    suggestedMin: -10,
                    stepSize: 1,
                    callback: function(value, index, values){
                      return  value +  '人'
                    }
                  }
                }]
              },
            }
          });
        </script>
    </div>

    <div calss="comments">
      <div class="comment">
        <% if @comments.present? %>
          <% @comments.each do |c|%>
            <div class="comment_box">
              <%= c.comment %>
              <ul class="comment_info">
                <li><%= c.user.name%></li>
                <li><%= c.created_at.strftime('%Y/%m/%d')%></li>
              </ul>
            </div>
          <% end %>
        <% else %>
          <p>コメントを書こう</p>
        <% end %>
      </div>
      <div class="comment_send">
        <%= form_with url: @comment do |f| %>
          <%= f.text_field :comment, class:"text_box" %>
          <%= f.submit "コメントする", class:"btn" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keep-Smart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
  </head>

  <body>
    <div class="header">
      <h2 class="header_title">Keep Smart</h2>
      <div class="header_right">
        <% if session[:user_id] %>
          <% current_user = User.find_by(id: session[:user_id]) %>
          <span class="header_user">ユーザー：<%= current_user.name %></span>
          <%= link_to "ログアウト", logout_users_path, method: "post", class: :header_parts  %>
          <%= link_to "体重入力", new_chart_path, class: :header_parts %>
        <% else %>
          <%= link_to "ログイン", login_users_path, class: :header_parts %>
          <%= link_to "新規登録", new_user_path, class: :header_parts %>
        <% end %>
      </div> 
    </div>
    <% if flash[:notice] %>
      <div class="flash">
      <%= flash[:notice] %>
      </div>
     <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/login_form.html.erb
<% if @error_message%>
  <div class="form-error">
    <%= @error_message %>
  </div>
<% end %>
<div class="login">
  <div class="login_form">
    <%= form_with(url: login_users_path, local: true ) do |f| %>
      <P>ユーザーネーム</p>
      <%= f.text_field :name  %>
      <p>パスワード</p>
      <%= f.password_field :password  %><br>
      <%= f.submit "ログイン", class: :login_btn %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="register">
  <div class="register_content">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :ユーザーネーム %><br>
      <%= f.text_field :name, placeholder: "3文字以上"  %><br>
      <%= f.label :パスワード %><br>
      <%= f.text_field :password, placeholder: "3文字以上" %><br>
      <%= f.label :身長 %><br>
      <%= f.number_field :height, placeholder: "例：170  (単位はcm)" %><br>
      <%= f.submit "新規登録", class: :register_btn %>
    <% end %>
  </div>
</div>